name: SurvivalTweaker
version: 1.0-SNAPSHOT
main: com.molean.rainvillage.survivaltweaker.SurvivalTweaker
api-version: 1.16
commands:
  spawn: {}
  menu: {}
  resource:
    permission: survivaltweaker.resource
  resource2:
    permission: survivaltweaker.resource2
  book:
    permission: survivaltweaker.book
  more:
    permission: survivaltweaker.more
  lore:
    permission: survivaltweaker.lore